services:
  localstack:
    image: localstack/localstack:3.3
    ports:
      - "4566:4566"    # Main entry point
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"